### PR TITLE
Dry up references to app name

### PR DESCRIPTION
**Pull request by acj**

### CODE REVIEW

**Comment by acj** [comment]
@cjbottaro @valo It's unclear whether this is the right repo for submitting PRs. This one is several useful merges ahead of the [original](https://github.com/cjbottaro/faktory_worker_ex) and is pointed to by the [Faktory wiki](https://github.com/contribsys/faktory/wiki/Related-Projects#workers), so here we are. If it would be better to submit them to the original repo to help everything converge, please let me know.

**Comment by cjbottaro** [comment]
I am super open to PRs. Big fan of Elixir and Faktory and am very motivated to work on them.

**Comment by valo** [comment]
@cjbottaro Thanks for starting the faktory_worker_ex project! Your work helped us tremendously with getting the workers online and crunching.

I pushed 2 PRs to the original repo, but haven't heard from you.  Depending on my free time I might be able to go back and create PRs for the changes on our repo. Unfortunately it will be a bit harder now, when we have several things piled up. Some help will be appreciated!

**Review by valo — APPROVED** [review]

**Comment by valo** [comment]
@acj Thanks for contributing ❤️💜💚

**Comment by acj** [comment]
Thanks, all! I have a couple more local branches that I'll push later today. I'll open those PRs against this repo for simplicity's sake, but I'd be happy to help migrate them back to the original repo if that's the consensus.

**Comment by cjbottaro** [comment]
I think there is something wrong with my notification settings; I didn't get emails for the issue and PRs opened on my repo. I'll get those merged in ASAP.

**Comment by cjbottaro** [comment]
@valo @acj I'm not sure the right forum for this discussion, but I've merged all the PRs on my repo, despite having some issues with one of them.

I voice my concerns in this comment (as well as ask a question): https://github.com/cjbottaro/faktory_worker_ex/pull/3#issuecomment-354354456

That comment also has a link to a commit in which I address all the issues. I'd like y'all to review that commit please.

I'd like to review all other changes/PRs, but not sure the best way to go about doing that. Maybe take all PRs (merged or otherwise) from this repo and open them against mine?

Also, I'm not sure what is up with my notifications. If I don't respond to an issue or PR within a few days just @ me, I definitely get emails for those.

Thanks!

**Comment by acj** [comment]
> Maybe take all PRs (merged or otherwise) from this repo and open them against mine?

That sounds good to me. Thanks for all of your work on this!

**Comment by valo** [comment]
> Maybe take all PRs (merged or otherwise) from this repo and open them against mine?

Sounds good to me. We can try to help as much as we can here. Especially with testing, as we already use this quite heavily in production. At some point we will switch to the original version of the library use this repo only for proposing fixes.

**Pull request merged**
